# Generated by Django 5.2.8 on 2026-04-08 08:03

import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('license', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('altPhone', models.CharField(blank=True, max_length=15, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('medical', models.TextField(blank=True, null=True)),
                ('maritalStatus', models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('jobType', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['driver_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('eway_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier_gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('goods_description', models.CharField(blank=True, max_length=300, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('route_from', models.CharField(blank=True, max_length=200, null=True)),
                ('route_to', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_days', models.IntegerField(blank=True, default=0, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Expiring Soon', 'Expiring Soon'), ('Critical', 'Critical')], default='Active', max_length=30)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LRBilty',
            fields=[
                ('lr_id', models.AutoField(primary_key=True, serialize=False)),
                ('lr_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('consignor', models.CharField(blank=True, max_length=200, null=True)),
                ('consignee', models.CharField(blank=True, max_length=200, null=True)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('freight', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In-Transit', 'In-Transit'), ('Billed', 'Billed')], default='Pending', max_length=30)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.driver')),
                ('eway_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.ewaybill')),
            ],
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='lr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.lrbilty'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Trip', 'In Trip'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=30)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_location', models.CharField(blank=True, max_length=200, null=True)),
                ('end_location', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Scheduled', 'Scheduled')], default='Scheduled', max_length=30)),
                ('distance', models.FloatField(default=0)),
                ('fuel_consumed', models.FloatField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('speed', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Moving', 'Moving'), ('Stopped', 'Stopped'), ('Idle', 'Idle')], default='Moving', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('toll_id', models.AutoField(primary_key=True, serialize=False)),
                ('toll_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main_app.models.toll_photo_path)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='lrbilty',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.vehicle'),
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('litres', models.FloatField()),
                ('price_per_litre', models.FloatField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main_app.models.fuel_photo_path)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.vehicle'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=30)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Income', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='main_app.trip')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='main_app.vehicle')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='main_app.vendor')),
            ],
        ),
    ]
