# Generated by Django 5.2.8 on 2026-04-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
    ]
