# Generated by Django 5.2.8 on 2025-12-01 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['driver_id']},
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='alt_phone',
            new_name='altPhone',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='job_type',
            new_name='jobType',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='marital_status',
            new_name='maritalStatus',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
