# Generated by Django 5.2.8 on 2026-04-21 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_inventory_reorder_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'managed': False, 'ordering': ['driver_id']},
        ),
        migrations.AlterModelOptions(
            name='ewaybill',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='financetransaction',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fuel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lrbilty',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='toll',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin / Owner'), ('Manager', 'Manager / Accountant'), ('Driver', 'Driver'), ('Vendor', 'Vendor')], default='Admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
