# Generated by Django 5.2.8 on 2025-12-03 05:28

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=50)),
                ('litres', models.FloatField()),
                ('price_per_litre', models.FloatField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main_app.models.fuel_photo_path)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('toll_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=50)),
                ('toll_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main_app.models.toll_photo_path)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
