# Generated by Django 6.0.6 on 2026-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_driver_options_alter_ewaybill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='driver',
            table='driver',
        ),
        migrations.AlterModelTable(
            name='ewaybill',
            table='eway_bill',
        ),
        migrations.AlterModelTable(
            name='financetransaction',
            table='finance_transaction',
        ),
        migrations.AlterModelTable(
            name='fuel',
            table='fuel',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
        migrations.AlterModelTable(
            name='lrbilty',
            table='lr_bilty',
        ),
        migrations.AlterModelTable(
            name='systemsetting',
            table='system_setting',
        ),
        migrations.AlterModelTable(
            name='toll',
            table='toll',
        ),
        migrations.AlterModelTable(
            name='tracking',
            table='tracking',
        ),
        migrations.AlterModelTable(
            name='trip',
            table='trip',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendor',
        ),
    ]
